#!/bin/bash

## This script first extracts the missing barcodes corresponding to bed files generated by each method
## It then extracts the sequences corresponding to each barcode and stores them into the out directory as
## read1_miss_{method}.fq, barcode_miss_{method}.fq etc

f1=$1 # piscem bed file
f2=$2 # chromap bed file
out=$3 # output directory that contains the missing barcode files
barcode_file=$4 # fastq barcode file of the overall sequence on which piscem/chromap bed file were generated
inp_read1=$5 # fastq read1 file of the overall sequence on which piscem/chromap bed file were generated
inp_read2=$6 # fastq read2 file of the overall sequence on which piscem/chromap bed file were generated

script1_dir="$(dirname "$0")"
$script1_dir/extract_miss_barcode.sh $f1 $f2 $out
$script1_dir/extract_seq.sh $out $barcode_file $inp_read1 $inp_read2

### Example
### bash helper_scripts/ext_miss_barcode_seq.sh \
### piscem_analysis/samp_1400_k23_psc_off\=true_ps_skip\=false_thr\=0.7/map.bed \
### chromap_analysis//map_out_samp_1400.txt \
### sub_seq \
### sub_seq/barcode.fq \
### sub_seq/read1_subsamp.fq \
### sub_seq/read2_subsamp.fq